---
- name: "Restart NetworkManager"
  ansible.builtin.service:
    name: "{{ hostvars[inventory_hostname]['network_manager_service'] }}"
    state: "restarted"
  when:
    - "hostvars[inventory_hostname]['network_manager'] is defined"
    - "hostvars[inventory_hostname]['network_manager'] != ''"
    - "hostvars[inventory_hostname]['network_manager'] |
       community.general.json_query(vars['network_manager_restart']) is
       defined"
    - "hostvars[inventory_hostname]['network_manager'] |
       community.general.json_query(vars['network_manager_restart']) == 'true'"
  vars:
    network_manager_restart: "[] | map(&restart || 'false', @) | [0]"
