---
- name: Enable network service
  ansible.builtin.service:
    name: "{{ hostvars[inventory_hostname]['network_scripts_service'] }}"
    enabled: "yes"
  when:
    - "(hostvars[inventory_hostname]['network_scripts_restart'] is defined and
      hostvars[inventory_hostname]['network_scripts_restart'] == 'true')"
    - "(hostvars[inventory_hostname]['58:network_scripts_triggers_type'] is
      defined and
      hostvars[inventory_hostname]['58:network_scripts_triggers_type'] ==
      'ifcfg')"
- name: Restart network service
  ansible.builtin.service:
    name: "{{ hostvars[inventory_hostname]['network_scripts_service'] }}"
    state: "restarted"
  when:
    - "(hostvars[inventory_hostname]['network_scripts_restart'] is defined and
      hostvars[inventory_hostname]['network_scripts_restart'] == 'true')"
    - "(hostvars[inventory_hostname]['58:network_scripts_triggers_type'] is
      defined and
      hostvars[inventory_hostname]['58:network_scripts_triggers_type'] ==
      'ifcfg')"
